# Data Processing Configuration

# Corpus Settings
corpus:
  raw_dir: "data/corpus/raw"
  processed_dir: "data/corpus/processed"
  validation_dir: "data/corpus/validation"
  file_pattern: "*.jsonl.gz"        # 若不是 .gz，請改為 "*.jsonl"
  batch_size: 500                   # 避免記憶體壓力，調降為 500

# Preprocessing Settings
preprocessing:
  min_segment_length: 100
  max_segment_length: 1000
  sentence_window: 10
  sentence_stride: 5
  remove_html: true
  normalize_whitespace: true
  lowercase: false

# Validation Settings
validation:
  check_md5: true
  validate_json: true
  sample_size: 500                 # 減少初期 sample size，避免空資料 crash
  log_dir: "logs/data_processing" # 請確認 logs 資料夾存在或程式會自動建立

# Storage Settings
storage:
  cache_dir: "data/cache"
  temp_dir: "data/temp"
  max_cache_size: "5GB"            # 降低初期快取空間限制，避免配額爆掉
